language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
    - '${NVM_PATH}_modules'
install:
  - yarn
  - cd functions && yarn && cd ..
script:
  - yarn lint
  - echo "Building..."
  - 'if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi'
  - 'if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi'
before_deploy:
  - echo "Deploying!"
deploy:
  - provider: firebase
    skip_cleanup: true
    'on':
      branch: master
    project: hoverboard-master
    token:
      secure: gE9Cy2NVCtbeXj4pDSgI/Wqm/orZnmX++vs5r8UFioFlA/HMWbbMn57KGDPSrZsf7/mi0LMb69UCY4UqLHNyTii66MOrpNaNjiR2jxoyqfjbZPisNCf74xpXxd3xwEMGd20lOzQkMz9yTUOiFaNohWCc0c0PRDuQn5NLVLqBE6jq4ZMLmy8khIqvJRTfnMx2qJBmwIfHvLDvsjW9mUmrLH/opGVOfrY2xrpV9R2BGvIwOiks31EYEfPQKi7h/zTSmMRVAQrrJiSvmP1PWxuXlRQFtpeTxM9s8BeciRcdGdsme9xi78X1bWq59g0ztTRS/MeTRVwRQZ7sY2/srEAF4mVIS55prKIbxqNGezvsv9Q2Z9VUorGTNzEcmbLlcMJ9OzqKteV3E5sy9g3E7z0YIVNEW22SqH4noLqu8uQQICnwQU3I+++jOqdOcJkXAhhT9p0zwfHP2edA6uJMsc1Q8D6gqRsKlT++IXE1ll2EyYKprAhgxRUTlFc29nGEDXTJrOyiiQxNU02088I7bxOOKqCVSeul5LGLxDGhI/Q5HHPD3ndfnDucXsBaAj1VASHCvlqFCRO0GS73KUNYtFqG61UKW6/uhQsHWe8ps+FWg1IYAUIMI0+aSi/OoK9J9tOXOnVgDnZ+76/JTQ7rugJUYF/+41SjNzu9nmlhMfVXjT0=
  - provider: firebase
    skip_cleanup: true
    'on':
      branch: develop
    project: hoverboard-dev
    token:
      secure: gE9Cy2NVCtbeXj4pDSgI/Wqm/orZnmX++vs5r8UFioFlA/HMWbbMn57KGDPSrZsf7/mi0LMb69UCY4UqLHNyTii66MOrpNaNjiR2jxoyqfjbZPisNCf74xpXxd3xwEMGd20lOzQkMz9yTUOiFaNohWCc0c0PRDuQn5NLVLqBE6jq4ZMLmy8khIqvJRTfnMx2qJBmwIfHvLDvsjW9mUmrLH/opGVOfrY2xrpV9R2BGvIwOiks31EYEfPQKi7h/zTSmMRVAQrrJiSvmP1PWxuXlRQFtpeTxM9s8BeciRcdGdsme9xi78X1bWq59g0ztTRS/MeTRVwRQZ7sY2/srEAF4mVIS55prKIbxqNGezvsv9Q2Z9VUorGTNzEcmbLlcMJ9OzqKteV3E5sy9g3E7z0YIVNEW22SqH4noLqu8uQQICnwQU3I+++jOqdOcJkXAhhT9p0zwfHP2edA6uJMsc1Q8D6gqRsKlT++IXE1ll2EyYKprAhgxRUTlFc29nGEDXTJrOyiiQxNU02088I7bxOOKqCVSeul5LGLxDGhI/Q5HHPD3ndfnDucXsBaAj1VASHCvlqFCRO0GS73KUNYtFqG61UKW6/uhQsHWe8ps+FWg1IYAUIMI0+aSi/OoK9J9tOXOnVgDnZ+76/JTQ7rugJUYF/+41SjNzu9nmlhMfVXjT0=
